FROM node:slim
WORKDIR /home/app/
COPY . .
#change to destination server
ENV BACKEND_SERVER="0.0.0.0"
#change to server port
ENV BACKEND_PORT="8000"
RUN sed -i "/server/ s/0.0.0.0/${BACKEND_SERVER}/" ./scripts/state.js
RUN sed -i "/port/ s/8000/${BACKEND_PORT}/" ./scripts/state.js
EXPOSE 3000
RUN ["npm", "ci"]
CMD ["node", "server.js"]