services:
  app:
    build: ./frontend
    ports:
      - "3000:3000"

  server:
    build: ./backend
    ports: 
      - "8000:8000"
    environment:
      ROCKET_ADDRESS: 0.0.0.0
      DB_SERVER: db
      DB_USER: mongo
      DB_PASSWD: passwd
      DB_PORT: 27017 
  
  db:
    image: mongo
    ports:
      - "27017:27017"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: passwd
    volumes:
      - ./backend/.db/data/db:/data/db