services:
  db:
    image: mongo
    ports:
      - "1027:27017"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: passwd
    volumes:
      - .db/data/db:/data/db