services:
  # server_api:
  #   build: .
  #   ports: 
  #     - "8000:8000"
  db:
    image: mongo
    ports:
      - "27017:27017"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: passwd
    volumes:
      - .db/data/db:/data/db