services:
  mfe-user:
    build:
      context: ../../mfe/Users/
      dockerfile: ../Dockerfile
      args:
        ARG_MFE_SERVER: "http://localhost:8080"
        ARG_CHAT_SERVER: "ws://localhost:8080/api/ws"
    ports:
      - 80

  mfe-room:
    build:
      context: ../../mfe/Rooms/
      dockerfile: ../Dockerfile
      args:
        ARG_MFE_SERVER: "http://localhost:8080"
        ARG_CHAT_SERVER: "ws://localhost:8080/api/ws"
    ports:
      - 80

  mfe-chat:
    build:
      context: ../../mfe/Chat/
      dockerfile: ../Dockerfile
      args:
        ARG_MFE_SERVER: "http://localhost:8080"
        ARG_CHAT_SERVER: "ws://localhost:8080/api/ws"
    ports:
      - 80

  mfe-host:
    build:
      context: ../../mfe/Freetext/
      dockerfile: ../Dockerfile
      args:
        ARG_MFE_SERVER: "http://localhost:8080"
        ARG_CHAT_SERVER: "ws://localhost:8080/api/ws"
    ports:
      - 80

  chat_server:
    build:
      context: ../../services/chat_server/
    ports:
      - 3100

  ingress:
    image: nginx
    volumes:
      - ../../mfe/nginx/mfe-prd-nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
    depends_on:
      - mfe-user
      - mfe-room
      - mfe-chat
      - mfe-host
