server {
	listen       80;
	listen  [::]:80;

	location /user/ {
		proxy_pass http://mfe-user/;
		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;
	}

	location /room/ {
		proxy_pass http://mfe-room/;
		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;
	}

	location /chat/ {
		proxy_pass http://mfe-chat/;
		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;
	}

	location /freetext/ {
		proxy_pass http://mfe-host/;
		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;
	}

	location /api/ws {
		proxy_pass http://chat_server:3100/ws;
		proxy_http_version 1.1;
		proxy_set_header Upgrade $http_upgrade;
		proxy_set_header Connection "upgrade";
	}
}
