apiVersion: v1
kind: Namespace
metadata:
  name: freetext
---
apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: null
  name: db-root-auth
  namespace: freetext
data:
  db-root-username: bW9uZ28=
  db-root-password: cGFzc3dk
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: freetext
data:
  rocket_address: 0.0.0.0
  db_server: db-svc
  db_port: "27017"
  app_server: 10.105.26.130
  app_port: "30000"
---
apiVersion: v1
kind: Service
metadata:
  name: db-svc
  namespace: freetext
spec:
  ports:
  - port: 27017
    protocol: TCP
---
kind: Endpoints
apiVersion: v1
metadata:
  name: db-svc
  namespace: freetext
subsets:
  - addresses:
    - ip: 10.105.26.17
    ports:
    - port: 27017
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rocket-depl
  labels:
    app: server
  namespace: freetext
spec:
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: rocket-container
          image: 0x1a0a/chat-app
          ports:
          - containerPort: 8000
          env:
          - name: ROCKET_ADDRESS
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: rocket_address
          - name: DB_SERVER
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: db_server
          - name: DB_PORT
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: db_port
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: db-root-auth
                key: db-root-username
          - name: DB_PASSWD
            valueFrom:
              secretKeyRef:
                name: db-root-auth
                key: db-root-password
---
apiVersion: v1
kind: Service
metadata:
  name: server-svc
  labels:
    app: server
  namespace: freetext
spec:
  selector:
    app: server
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30000
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    app: frontend
  namespace: freetext
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - image: 0x1a0a/chat-app-frontend
        name: frontend-server
        env:
        - name: APP_SERVER
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: app_server
        - name: APP_PORT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: app_port
        lifecycle:
          postStart:
            exec:
              command: ["/usr/share/nginx/html/apply-config.sh", "/usr/share/nginx/html"]
---
apiVersion: v1
kind: Service
metadata:
  name: app-svc
  labels:
    app: frontend
  namespace: freetext
spec:
  ports:
    - port: 8080
      targetPort: 80
      nodePort: 30080
  selector:
    app: frontend
  type: NodePort
