apiVersion: v1
kind: Namespace
metadata:
  name: freetext
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
  namespace: freetext
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: null
  name: db-root-auth
  namespace: freetext
data:
  db-root-password: bW9uZ28=
  db-root-username: cGFzc3dk
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: freetext
data:
  rocket_address: 0.0.0.0
  db_server: db-svc
  db_port: "27017"
  app_server: 10.105.26.130
  app_port: "30000"
  web_port: "3000"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-depl
  labels:
    app: db
  namespace: freetext
spec:
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: mongodb-container
        image: mongo
        args: ["--dbpath","/data/db"]
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: db-root-auth
              key: db-root-username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-root-auth
              key: db-root-password
        volumeMounts:
        - name: mongo-data
          mountPath: "/data/db"
      volumes:
      - name: mongo-data
        persistentVolumeClaim:
          claimName: db-pvc
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: db
  name: db-svc
  namespace: freetext
spec:
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    app: db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rocket-depl
  labels:
    app: server
  namespace: freetext
spec:
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: rocket-container
          image: 0x1a0a/chat-app
          ports:
          - containerPort: 8000
          env:
          - name: ROCKET_ADDRESS
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: rocket_address
          - name: DB_SERVER
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: db_server
          - name: DB_PORT
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: db_port
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: db-root-auth
                key: db-root-username
          - name: DB_PASSWD
            valueFrom:
              secretKeyRef:
                name: db-root-auth
                key: db-root-password
---
apiVersion: v1
kind: Service
metadata:
  name: server-svc
  labels:
    app: server
  namespace: freetext
spec:
  selector:
    app: server
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30000
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    app: frontend
  namespace: freetext
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - image: 0x1a0a/chat-app-frontend
        name: frontend-server
        env:
        - name: APP_SERVER
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: app_server
        - name: APP_PORT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: app_port
        - name: WEB_PORT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: web_port
---
apiVersion: v1
kind: Service
metadata:
  name: app-svc
  labels:
    app: frontend
  namespace: freetext
spec:
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30080
  selector:
    app: frontend
  type: NodePort
